# Required to run your project under the correct environment.
language: php

# Versions of PHP you want your project run with.
php:
#  - 5.4
#  - 5.5
  - 5.6
  - 7.0
  - hhvm

# Commands to be run before your environment runs.
before_script:
  - composer self-update
  - composer install --no-interaction --dev
  - touch ./database/database.sqlite
  - composer self-update
  - composer install -n --prefer-source
  - php artisan migrate --env=testing --database=testing
  - php artisan migrate --env=testing --seed -n --force  --database=testing

# Commands you want to run that will verify your build.
#script: phpunit
script:
  - phpunit

# allow_failures: Allow this build to fail under the specified environments.
# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
  allow_failures:

  fast_finish: true

# Customize when the notification emails are sent.
notifications:
    on_success: always
    on_failure: always